apiVersion: v1
kind: Template
metadata:
  annotations:
    description: CoolStore Microservices Web UI Template
    iconClass: icon-java
    tags: microservice,jboss,spring
  name: coolstore
objects:
# UI
# - apiVersion: v1
#   kind: ImageStream
#   metadata:
#     name: web-ui
#     labels:
#       app: coolstore
#       component: web-ui
#   spec:
#     tags:
#     - name: latest
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: web-ui
    labels:
      app: coolstore
      component: web-ui
  spec:
    replicas: 1
    selector:
      deploymentconfig: web-ui
    strategy:
      resources: {}
      type: Recreate
    template:
      metadata:
        labels:
          app: coolstore
          component: web-ui
          deploymentconfig: web-ui
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: COOLSTORE_GW_SERVICE
            value: ${CATALOG_SERVICE}
          - name: HOSTNAME_HTTP
            value: web-ui:8080
          image: web-ui
          imagePullPolicy: Always
          name: web-ui
          ports:
          - containerPort: 8080
            protocol: TCP
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 50m
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - web-ui
        from:
          kind: ImageStreamTag
          name: web-ui:latest
          namespace: ${IMAGE_NAMESPACE}
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: coolstore
      component: web-ui
    name: web-ui
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentconfig: web-ui
- apiVersion: v1
  kind: Route
  metadata:
    name: web-ui
    labels:
      app: coolstore
      component: web-ui
  spec:
    to:
      kind: Service
      name: web-ui
parameters:
- description: Catalog service name exposing a REST API for the product list
  displayName: Catalog Service Name
  name: CATALOG_SERVICE
  required: true
  value: catalog
- displayName: Image Namespace
  description: The namespace to push the built Web UI images to
  name: IMAGE_NAMESPACE
  value: cicd
  required: true
- displayName: Image Version
  description: Web UI image versions to deploy
  name: IMAGE_VERSION
  required: true
  value: latest